using Chapter_2.Services.Interfaces;

namespace Chapter_2.Services
{
    public class OnboardingChatGPTService : ILLMService
    {
        public string ProviderName => "chatgpt";

        private readonly HttpClient _httpClient;
        private readonly ILogger<OnboardingChatGPTService> _logger;

        public OnboardingChatGPTService(
            HttpClient httpClient,
            ILogger<OnboardingChatGPTService> logger)
        {
            _httpClient = httpClient;
            _logger = logger;
        }

        public async Task<string> GenerateTestCodeAsync(string prompt, string context)
        {
            _logger.LogInformation("Generating test code with ChatGPT for {Context}", context);

            // Simulate API call
            await Task.Delay(500);

            return $@"// Generated by ChatGPT for: {context}
[Test]
public void Should_Correctly_Calculate_Total()
{{
    // Arrange
    var calculator = new Calculator();
    
    // Act
    var result = calculator.Add(2, 3);
    
    // Assert
    Assert.That(result, Is.EqualTo(5));
}}";
        }

        public async Task<TestGenerationResult> GenerateTestWithAnalysisAsync(string code, string context)
        {
            var generated = await GenerateTestCodeAsync(code, context);

            return new TestGenerationResult
            {
                GeneratedCode = generated,
                Explanation = "Generated unit test for calculator functionality",
                Assumptions = new[] { "Calculator class exists", "Add method takes two integers" },
                Confidence = 0.92m
            };
        }

        public async Task<decimal> GetConfidenceScoreAsync(string code, string test)
        {
            // Simple confidence calculation
            var coverage = test.Length / (double)Math.Max(code.Length, 1);
            return (decimal)Math.Min(coverage * 1.5, 1.0);
        }
    }

    public class OnboardingClaudeService : ILLMService
    {
        public string ProviderName => "claude";

        public Task<string> GenerateTestCodeAsync(string prompt, string context)
        {
            return Task.FromResult($@"// Generated by Claude for: {context}
[Fact]
public async Task CalculateTotal_ReturnsCorrectSum()
{{
    // Given
    var sut = new ShoppingCart();
    sut.AddItem(new Item(""Apple"", 1.99m));
    sut.AddItem(new Item(""Banana"", 0.99m));
    
    // When
    var total = await sut.CalculateTotalAsync();
    
    // Then
    Assert.Equal(2.98m, total);
}}");
        }

        public Task<TestGenerationResult> GenerateTestWithAnalysisAsync(string code, string context)
        {
            return Task.FromResult(new TestGenerationResult
            {
                GeneratedCode = "// Claude generated test",
                Explanation = "Test for async shopping cart calculation",
                Confidence = 0.88m
            });
        }

        public Task<decimal> GetConfidenceScoreAsync(string code, string test)
        {
            return Task.FromResult(0.85m);
        }
    }

    public class OnboardingDeepSeekService : ILLMService
    {
        public string ProviderName => "deepseek";

        public Task<string> GenerateTestCodeAsync(string prompt, string context)
        {
            return Task.FromResult($@"// Generated by DeepSeek for: {context}
[Test]
public void ComplexCalculation_WorksWithEdgeCases()
{{
    // Test multiple edge cases
    var testCases = new[]
    {{
        new {{ Input = 0, Expected = 0 }},
        new {{ Input = int.MaxValue, Expected = int.MaxValue }},
        new {{ Input = -1, Expected = -1 }}
    }};
    
    foreach (var testCase in testCases)
    {{
        var result = Calculator.Process(testCase.Input);
        Assert.AreEqual(testCase.Expected, result);
    }}
}}");
        }

        public Task<TestGenerationResult> GenerateTestWithAnalysisAsync(string code, string context)
        {
            return Task.FromResult(new TestGenerationResult
            {
                GeneratedCode = "// DeepSeek generated test",
                Explanation = "Comprehensive edge case testing",
                Confidence = 0.90m
            });
        }

        public Task<decimal> GetConfidenceScoreAsync(string code, string test)
        {
            return Task.FromResult(0.90m);
        }
    }
}
