// <auto-generated />
using System;
using Chapter_7.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chapter_7.Migrations
{
    [DbContext(typeof(PipelineDbContext))]
    partial class PipelineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chapter_7.Data.Entities.AdaptationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdaptationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdaptationPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImpactScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("ImplementedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdaptationId")
                        .IsUnique();

                    b.HasIndex("PipelineId");

                    b.ToTable("AdaptationEvents", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.OptimizationOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Effort")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Impact")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("ImplementedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OpportunityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.HasIndex("PipelineId");

                    b.ToTable("OptimizationOpportunities", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TestCoverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalLines")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Language");

                    b.HasIndex("PipelineId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Pipelines", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RawLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RootCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FailureType");

                    b.HasIndex("RunId");

                    b.ToTable("PipelineFailures", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("PipelineRuns", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AverageDuration")
                        .HasColumnType("int");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<decimal?>("SuccessRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId", "StageId")
                        .IsUnique();

                    b.ToTable("PipelineStages", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PredictionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Accuracy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModelData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "Version")
                        .IsUnique();

                    b.ToTable("PredictionModels", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PredictionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PredictionData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredictionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PredictionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("PipelineId");

                    b.HasIndex("PredictionId")
                        .IsUnique();

                    b.ToTable("PredictionResults", (string)null);
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.AdaptationEvent", b =>
                {
                    b.HasOne("Chapter_7.Data.Entities.Pipeline", "Pipeline")
                        .WithMany("AdaptationEvents")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.OptimizationOpportunity", b =>
                {
                    b.HasOne("Chapter_7.Data.Entities.Pipeline", "Pipeline")
                        .WithMany("OptimizationOpportunities")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineFailure", b =>
                {
                    b.HasOne("Chapter_7.Data.Entities.PipelineRun", "Run")
                        .WithMany("Failures")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineRun", b =>
                {
                    b.HasOne("Chapter_7.Data.Entities.Pipeline", "Pipeline")
                        .WithMany("Runs")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineStage", b =>
                {
                    b.HasOne("Chapter_7.Data.Entities.Pipeline", "Pipeline")
                        .WithMany("Stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PredictionResult", b =>
                {
                    b.HasOne("Chapter_7.Data.Entities.PredictionModel", "Model")
                        .WithMany("PredictionResults")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chapter_7.Data.Entities.Pipeline", "Pipeline")
                        .WithMany("PredictionResults")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.Pipeline", b =>
                {
                    b.Navigation("AdaptationEvents");

                    b.Navigation("OptimizationOpportunities");

                    b.Navigation("PredictionResults");

                    b.Navigation("Runs");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PipelineRun", b =>
                {
                    b.Navigation("Failures");
                });

            modelBuilder.Entity("Chapter_7.Data.Entities.PredictionModel", b =>
                {
                    b.Navigation("PredictionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
