using Chapter_3.Attributes;
using Chapter_3.Models.Domain;
using Chapter_3.Models.Requests;
using System.ComponentModel.DataAnnotations;

namespace Chapter_3.Models.Supporting
{
    // Models/Requests/UserEdit.cs
    public class UserEdit
    {
        [Required]
        [MinLength(1)]
        [MaxLength(10000)]
        public string Content { get; set; } = string.Empty;

        [Required]
        [MinLength(10)]
        [MaxLength(500)]
        public string Intent { get; set; } = string.Empty;

        [Required]
        public string EditorId { get; set; } = string.Empty;

        public string EditType { get; set; } = "modification"; // addition, modification, deletion, refactor
        public string[] AffectedLines { get; set; } = Array.Empty<string>();
        public string[] ChangedSections { get; set; } = Array.Empty<string>();
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [Range(1, 100)]
        public int Priority { get; set; } = 5;

        public Dictionary<string, object> Metadata { get; set; } = new()
        {
            ["autoGenerated"] = false,
            ["reviewed"] = false
        };
    }

    // Models/Responses/ReviewSessionResponse.cs
    public class ReviewSessionResponse
    {
        [Required]
        public string SessionId { get; set; } = string.Empty;

        public string Status { get; set; } = "awaiting_review";
        public string[] ReviewersAssigned { get; set; } = Array.Empty<string>();
        public TimeSpan EstimatedReviewTime { get; set; }
        public ReviewChecklistItem[] ReviewChecklist { get; set; } = Array.Empty<ReviewChecklistItem>();
        public string WorkspaceUrl { get; set; } = string.Empty;
        public InitialQuestion[] InitialQuestions { get; set; } = Array.Empty<InitialQuestion>();
        public string AiConfidenceStatement { get; set; } = string.Empty;
        public JudgmentArea[] AreasNeedingHumanJudgment { get; set; } = Array.Empty<JudgmentArea>();
        public CollaborationTools AvailableTools { get; set; } = new();
        public string[] QuickActions { get; set; } = Array.Empty<string>();
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? ExpiresAt { get; set; }

        // Session progress tracking
        public int EditCount { get; set; }
        public int ClarificationCount { get; set; }
        public double ProgressPercentage { get; set; }

        // Additional metadata
        public Dictionary<string, object> Metadata { get; set; } = new();
    }

    // Models/Responses/HumanReviewError.cs
    public class HumanReviewError
    {
        [Required]
        public string ErrorCode { get; set; } = string.Empty;

        [Required]
        public string Message { get; set; } = string.Empty;

        public string[] RequiredElements { get; set; } = Array.Empty<string>();
        public string[] MissingElements { get; set; } = Array.Empty<string>();
        public string Suggestion { get; set; } = string.Empty;
        public string[] ContextEnhancementPrompts { get; set; } = Array.Empty<string>();
        public string[] RecoveryActions { get; set; } = Array.Empty<string>();
        public DateTime ReportedAt { get; set; } = DateTime.UtcNow;

        // Additional error details
        public string ErrorType { get; set; } = "validation"; // validation, business, system
        public string ReferenceId { get; set; } = Guid.NewGuid().ToString();
        public Dictionary<string, object> Details { get; set; } = new();
    }

    // Models/Requests/ReviewRequest.cs
    public class ReviewRequest
    {
        [Required]
        [ValidateGeneratedTest]
        public GeneratedTest GeneratedContent { get; set; } = new();

        [Required]
        public ReviewContext Context { get; set; } = new();

        [Required]
        [MinLength(20)]
        [MaxLength(2000)]
        public string ReviewerGuidance { get; set; } = string.Empty;

        [Required]
        public SubmissionMetadata SubmissionMetadata { get; set; } = new();

        // Additional configuration
        public string[] PreferredReviewers { get; set; } = Array.Empty<string>();
        public string Priority { get; set; } = "normal"; // low, normal, high, urgent
        public bool EnableRealTimeCollaboration { get; set; } = true;
        public bool AutoSuggestImprovements { get; set; } = true;
        public string[] ReviewCategories { get; set; } = Array.Empty<string>();

        // Time constraints
        public DateTime? Deadline { get; set; }
        public int? EstimatedEffortMinutes { get; set; }

        public Dictionary<string, object> AdditionalSettings { get; set; } = new();
    }
}
