/*
1. POST /api/testgen - Generate Test Case

// Example request body
{
  "prompt": "Create a login test",
  "llmProvider": "chatgpt",
  "context": "Generate a complete test case",
  "urgency": 2
}

// Example response
{
  "generatedCode": "test('login', ...)",
  "testFramework": "playwright",
  "explanation": ["Generated by AI"],
  "estimatedComplexity": 3,
  "potentialFlakyPoints": ["Fixed delays"],
  "chosenProvider": "chatgpt"
}
*/



/*
2. POST /api/testgen/analyze/flaky - Analyze Flaky Tests
typescript
// Example request body
{
  "testRuns": [...],
  "analysisType": "flaky-pattern",
  "confidenceThreshold": 0.75
}
*/


/*

3. Error Responses
The component handles all error types from your backend:

400 Bad Request (validation errors)

503 Service Unavailable (AI provider issues)

500 Internal Server Error (unexpected errors)

*/


